name: condaBuild
on: [workflow_dispatch]
jobs:
  check_mac_installation:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: intelMacConda

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          auto-update-conda: true

      - name: install pyPDAF
        shell: bash -el {0}
        run: |
          conda install python anaconda-client conda-build conda-verify
          anaconda login --username yumengch --password ${{ secrets.ANACONDA }}
          conda  config --set anaconda_upload yes
          conda-build -c conda-forge -c intel conda.recipe/
